language: java

addons:
  sonarcloud:
    organization: "wouternoordhof-github"


script:
  - sonar-scanner

after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn jacoco:report coveralls:report